import type { ProvinceItem } from "./footprint.types";

export const footprintData: ProvinceItem[] = [
  {
    id: 1,
    code: "01",
    name: "Kabul",
    region: "Operational Hub",
    x: 55,
    y: 52,
    color: "#F59E0B",
    description: "Central coordination point for national operations.",
  },
  {
    id: 2,
    code: "02",
    name: "Balkh",
    region: "Active Region",
    x: 58,
    y: 22,
    color: "#0EA5B7",
    description: "Northern regional activity and implementation support.",
  },
  {
    id: 3,
    code: "03",
    name: "Herat",
    region: "Active Region",
    x: 12,
    y: 50,
    color: "#0EA5B7",
    description: "Western regional field coverage and partner support.",
  },
  {
    id: 4,
    code: "04",
    name: "Nangarhar",
    region: "Active Region",
    x: 73,
    y: 58,
    color: "#0EA5B7",
    description: "Eastern regional operations and field access support.",
  },
  {
    id: 5,
    code: "05",
    name: "Badakhshan",
    region: "Active Region",
    x: 82,
    y: 12,
    color: "#0EA5B7",
    description: "Northeastern activity area and extended regional reach.",
  },
];